version: '3.8'

services:
  health-checker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=http://database:5432
      - CACHE_URL=http://redis:6379
      - API_URL=http://api:8000
      - MONITORING_URL=http://prometheus:9090
    depends_on:
      - database
      - redis
      - api
      - prometheus

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=healthcheck
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  api:
    image: nginx:alpine
    ports:
      - "8000:80"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
