version: '3.8'

services:
  system-monitor:
    build: .
    container_name: system-monitor
    ports:
      - "8080:8080"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/rootfs
    pid: "host"
    privileged: true
    restart: unless-stopped
